# Calculate similarities among users derived from their interactions with films

Given a user-movie matrix, finish the function to calculate the similarity between users. 
```
data = [[0,1,0,1,1],
        [0,0,0,0,1],
        [1,0,0,0,0],
        [1,1,0,0,0]]
```
Each row is a user. Each column is a movie. 1 means the user watched that movie

Answer: To resolve this, one can calculate cosine similarity, cosine similarity = A*B/||A|| ||B||

In [4]:
import numpy as np
def cosine_similarity(matrix):
    matrix = np.array(matrix)
    # get A * B
    dot_product = np.dot(matrix, matrix.T)
    # get L2 norm for A 
    magnitude = np.linalg.norm(matrix, axis = 1)
    denominator = np.outer(magnitude, magnitude)
    similarity = dot_product / np.clip(denominator, 0.0000001, None)
    return similarity

In [6]:
if __name__ == "__main__":
    user_movie = [[0,1,0,1,1],
                [0,0,0,0,1],
                [1,0,0,0,0],
                [1,1,0,0,0]]
    user_movie = np.array(user_movie)
    user_similarity = cosine_similarity(user_movie)
    movie_similarity = cosine_similarity(user_movie.T)
    print(user_similarity)
    print(movie_similarity)

[[1.         0.57735027 0.         0.40824829]
 [0.57735027 1.         0.         0.        ]
 [0.         0.         1.         0.70710678]
 [0.40824829 0.         0.70710678 1.        ]]
[[1.         0.5        0.         0.         0.        ]
 [0.5        1.         0.         0.70710678 0.5       ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.70710678 0.         1.         0.70710678]
 [0.         0.5        0.         0.70710678 1.        ]]
